### ISSUE TITLE
"No Group Integration" option UAA-LDAP integration does not work as expected

### ISSUE THREAD

**Issue by wolfgangkoch** [cloudfoundry/uaa#697]
### What version of UAA are you running?

UAA 3.8.0

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

1) I integrated an ApacheDS as an LDAP to UAA. The Group Mapping configuration was set to "No Group Integration".
2) I logged in via an user created through ApacheDS. 
3) I assigned the LDAP user a group using the UAAC.
4) I logged in with the user again.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected the LDAP user to still have the group assigned to it.

### What did you see instead?

The groups (scopes) for the LDAP user was reset in UAA. The group assignment was lost after the re-login.

Please include UAA logs if available.

**Comment by jhamon** [comment]
Can retry this with the latest uaac? This sounds like a symptom of a bug related to the creation of group memberships that has been fixed in uaac 4.0.0.

**Comment by Ineedthisforwork** [comment]
The problem is still there with version 4.5.
Any other ideas?

This is the LDAP part from the uaa.yml:
spring_profiles: ldap,default,hsqldb
ldap:
  profile:
    file: ldap/ldap-simple-bind.xml
  base:
    url: 'ldap://localhost:10390/'
    mailAttributeName: mail
    userDnPattern: 'cn={0},ou=people,dc=example,dc=com'

**Comment by jhamon** [comment]
Did you try the latest uaac as I suggested earlier? A previous version of uaac had a bug where group memberships were created with `"origin": "ldap"`. These were lost / deleted the next time the user authenticates because those group memberships are not derived from information in the ldap store.

The most recent uaac fixes this bug, and sets `"origin":"uaa"` when an admin wants to assign memberships using uaac. You can try, or if you use curl to call [the API](https://docs.cloudfoundry.org/api/uaa/version/4.6.0/index.html#add-member) yourself.

**Comment by Ineedthisforwork** [comment]
Thank you for your answer. I read "uaa" instead of "uaac" in your first answer. Using the new uaac fixed the problem.

**Comment by Ineedthisforwork** [comment]
close #697

**Comment by wolfgangkoch** [comment]
Thank you for your quick help @jhamon !
