### ISSUE TITLE
Slowdown with /Users queries starting in 4.5.0

### ISSUE THREAD

**Issue by drennalls** [cloudfoundry/uaa#704]
We've noticed some slowdowns with UAA on a dev deployment of PCF where ERT was upgraded from https://docs.pivotal.io/pivotalcf/1-11/pcf-release-notes/runtime-rn.html#1.11.5 (w/UAA 4.1.0) to https://docs.pivotal.io/pivotalcf/1-11/pcf-release-notes/runtime-rn.html#1.11.12 (w/UAA 4.5.0). After the upgrade queries to `/Users` seem to take really long. For e.g. a root zone with 40+ users takes around 20+ seconds to return result to `/Users` query. I was able to reproduce the same thing with UAA apps on PCF dev, one app is 4.4.0 and one is 4.5.0..  I couldn't get them to run against mysql (which is what we're using and likely make things slightly slower I'm guessing) for some reason, so they're using the in memory hsqldb but I can still see the performance diff. The same query (list 200 users) done against uaa 4.4.0 takes ~600ms, but takes 8-9 seconds on the 4.5.0 app. 

Reproduction steps..
4.4.0 app
```
git clone https://github.com/cloudfoundry/uaa.git
cd uaa
git checkout tags/4.4.0 -b 4.4.0
./gradlew clean package
./gradlew manifests -Dapp=uaa440 -Dapp-domain=local.pcfdev.io
cf push uaa440 -f build/sample-manifests/uaa-cf-application.yml
uaac target https://uaa440.local.pcfdev.io
uaac token client get admin -s adminsecret
for num in {1..200}; do user=user${num}; echo "$user"; uaac user add user${num} -p password --email "$user@test.io"; done
```

timing w/4.4.0..
```
13:47 $ python -m timeit "__import__('os').system('uaac users --count 200 >/dev/null')"
10 loops, best of 3: 585 msec per loop
```

4.5.0 app
```
git clone https://github.com/cloudfoundry/uaa.git
cd uaa
git checkout tags/4.5.0 -b 4.5.0
./gradlew clean package
./gradlew manifests -Dapp=uaa450 -Dapp-domain=local.pcfdev.io
cf create-service p-mysql 512mb uaa450-db
cf push uaa450 -f build/sample-manifests/uaa-cf-application.yml
uaac target --skip-ssl-validation https://uaa450.local.pcfdev.io
uaac token client get admin -s adminsecret
for num in {1..200}; do user=user${num}; echo "$user"; uaac user add user${num} -p password --email "$user@test.io"; done
```
timing w/4.5.0..
```
13:51 $ python -m timeit "__import__('os').system('uaac users --count 200 >/dev/null')"
10 loops, best of 3: 8.51 sec per loop
```

**Comment by fhanik** [comment]
Thanks for the report, we will prioritize this one

**Comment by fhanik** [comment]
Recently introduced metrics show this

    {
      "lastRequests": [
        {
          "uri": "/uaa/Users",
          "uriGroup": {
            "pattern": "/Users/**",
            "group": "/users",
            "limit": 10000,
            "category": "API"
          },
          "statusCode": 200,
          "requestStartTime": 1506462263235,
          "requestCompleteTime": 1506462289275,
          "databaseQueryTime": 16884,
          "nrOfDatabaseQueries": 18009
        }
      ]
    }

18009 queries seems a bit excessive. Will dig into this.

**Comment by fhanik** [comment]
Count: 5600

    "insert into groups ( id,displayName,description,created,lastModified,version,identity_zone_id ) values (?,?,?,?,?,?,?)" 

Count: 5600

    "insert into groups ( id,displayName,description,created,lastModified,version,identity_zone_id ) values (?,?,?,?,?,?,?)

And the culprit is doing an `INSERT` followed by `SELECT` for each default group in the zone

**Comment by fhanik** [comment]
Fixed via https://github.com/cloudfoundry/uaa/commit/c793bb07060a552c968e95be8e9ddce0766558aa

**Comment by drennalls** [comment]
Thanks @fhanik ! How can I query those metrics you mentioned or are they only in `develop` branch ? 
Also I built against `develop` and tried the same test and although it's faster is still not back to `4.4.0` levels (e.g. querying 1000 users on 4.4.0 is ~1.9s , 4.6.0 it's ~42s and on dev ~9.7s on my setup). So I was just wondering what the expectation is perf-wise going forward whether things will go back to the 4.4.0 numbers.

**Comment by fhanik** [comment]
@drennalls - I have reopened this to further optimize it. It has to do with a feature where we added `default user groups` to zones, and now it does a N fetch of groups for every user.

In the meantime, there is a work around that will also work on 4.5.0
https://docs.cloudfoundry.org/api/uaa/version/4.6.0/index.html#list-with-attribute-filtering

if you specify the `attributes` query parameter on your call to `/Users` and that parameter does not have `groups` as part of the value, it will omit fetching groups all together.

Let me know if that solves it for you in the meantime.

**Comment by fhanik** [comment]
@drennalls Caching restored in https://github.com/cloudfoundry/uaa/commit/eefd4c9648178b78eaa9529ae681ad81a4abec1c

**Comment by drennalls** [comment]
@fhanik Thanks for the attribute-filtering tip :). That does really help things quite a bit when constructing the request manually, however I don't see a way to make use of it via the cf-java-client API for UAA, based on [ListUsersRequest](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/users/_ListUsersRequest.java) and [PaginatedAndSortedRequest](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/PaginatedAndSortedRequest.java) which it's based on unless I'm missing something.

**Comment by fhanik** [comment]
@drennalls not familiar with the cf-java-client, so not sure how to pass in query arguments.

Let me know if `develop` has restored what you were looking for. I believe 4.4.0 had an in memory cache. we now have the similar cache, the new one has expiring values to save server side resources.
