### ISSUE TITLE
UAA login pages are insufficiently customisable

### ISSUE THREAD

**Issue by 46bit** [cloudfoundry/uaa#734]
### What version of UAA are you running?

This is present in `v4.7.2`.

### How are you deploying the UAA?

Using `cf-release`.

### What did you do?

Tried to alter UAA's authorisation webpages.

### What did you expect to see?

We expected a built-in way to modify these pages, for instance by overridding the HTML templates in `server/src/main/resources/templates/web`.

### What goal are you trying to achieve with the UAA?

As part of GOV.UK, we have to follow an organisational style-guide and accessibility guidelines. We'd like to customise the UAA webpages to meet these requirements. 

### What did you see instead?

The built-in customisation options are insufficient:

* The [`branding` properties](https://github.com/cloudfoundry/uaa-release/blob/f34af8841d4dc61663f273e7b8452bdc5fd413ec/jobs/uaa/spec#L252-L273) can only change things like the name and logo.
* The `asset_base_url` property can be used to load custom CSS but [is documented as deprecated](https://github.com/cloudfoundry/uaa-release/blob/f34af8841d4dc61663f273e7b8452bdc5fd413ec/jobs/uaa/spec#L274-L276).
* There is no way to alter the HTML templates short of maintaining our own BOSH release.

We're using `asset_base_url` for now to specify custom CSS. As it is marked deprecated, we implemented an automatic test that it still works. We've also implemented tests that UAA's templates have not changed very much and that our stylesheet still works.

### Why is this an issue?

We think that a lot of organisations have or will have this same issue, and that maintaining our own BOSH release would be a lot of work just to change these pages. 

18F have a [separate BOSH release](https://github.com/18F/uaa-customized-boshrelease) that deploys their own custom pages, but this is quite unpleasant and has frightening comments.

An in-built solution, or guidance, on modifying these pages would seem a good idea.

**Comment by brittag** [comment]
Thanks for filing this! Yes, our 18F/cloud.gov team has this need too, and I agree that this is likely to be common across many organizations, especially in governments and other regulated environments.

As an example, among our other needs for customizing our login pages, we have a specific critical requirement: [AC-8 in the NIST standard for security controls](https://nvd.nist.gov/800-53/Rev4/control/AC-8). This requires U.S. federal systems like ours to warn readers that their actions may be monitored and recorded. They must explicitly acknowledge that warning (in our case, by clicking our "agree and continue" button) before we can present them with login options.

**Comment by sreetummidi** [comment]
We don't have plans to support this level of customization with the UI.

**Comment by mogul** [comment]
@sreetummidi can you suggest other options? Previously the login app was separate from the UI, but I don't think it's possible to make our own anymore... Is it?

**Comment by keymon** [comment]
> We don't have plans to support this level of customization with the UI.

@sreetummidi I think this feature request is important, and even if there are no plans for your team to implement it, we can discuss alternate approaches:

 - Would you welcome a PR?
 - Can we document a way to customise this login page?

**Comment by keymon** [comment]
Other use case: We have several CF installations using a shared UAA installation as IDP. We do not want the user to go to a  login page of the local CF that is not really being use, to then have to click on a small link in the bottom to go to the IDP (also UAA) login page which looks the same. 

It is a confusing user experience, and we want to offer an automated redirect to the IDP instead.

**Comment by ge-enrique-cano** [comment]
This is also an issue for us. We have ended up maintaining our own fork of UAA because of the login pages customisations.

**Comment by MatthiasWinzeler** [comment]
@keymon stumbled upon your question while looking for branding - your use case is solved with https://github.com/cloudfoundry/uaa/issues/615.

**Comment by mogul** [comment]
Curses, ours still isn't because we have multiple IdPs configured (visible after you click): 
https://login.fr.cloud.gov/login

**Comment by 46bit** [comment]
We use email/password login *and* an OAuth one, so I think we're still stuck too :-(
